---
- name: Deploy Web Application
  hosts: webservers
  become: true
  roles:
    - role: webserver

  tasks:
    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: present

    - name: Deploy Sample Web Application
      copy:
        src: "{{ playbook_dir }}/roles/webserver/templates/index.html.j2"
        dest: /usr/share/nginx/html/index.html
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

